### ISSUE TITLE
What targets are supported?

### ISSUE THREAD

**Issue by sjalloq** [ARMmbed/mbed-js-v2#4]
I'm trying to build the example for the NUCLEO_F767ZI board and building the project fails.

`[14:23:06] ChildProcessError: `python /mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py NUCLEO_F767ZI` failed with code 1
    at ChildProcess.<anonymous> (/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)`

**Comment by sjalloq** [comment]
So after reading up on node.js and how to get stdout piped through, it looks like there's an issue with a pin define in PinNames.h for the STM parts.  In targets.json there is some sort of config defined for 'd11_configuration' which uses macro 'STM32_D11_SPI_ETHERNET_PIN'.

If I edit PinNames.h to use what looks like the default, PA_7, then the error disappears and the compile continues.

STDOUT of the error here:

`[14:57:45] Using gulpfile /mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/Gulpfile.js
[14:57:47] Starting 'bundle'...
[14:57:47] Starting 'pip-requirements'...
[14:57:47] Starting 'make-build-dir'...
[14:57:47] Finished 'make-build-dir' after 227 μs
[14:57:47] Finished 'bundle' after 119 ms
[14:57:49] Finished 'pip-requirements' after 2.12 s
[14:57:49] Starting 'cppify'...
[14:57:49] Starting 'generate-pins'...
[14:57:49] Finished 'cppify' after 76 ms
Traceback (most recent call last):
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 250, in <module>
    main()
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 240, in main
    pins = enumerate_pins(pins_file, [os.path.dirname(__file__)] + list(includes), defines)
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 159, in enumerate_pins
    return visitor.visit(parsed_ast)
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 108, in visit
    value = value or self.visit(child_node)
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 108, in visit
    value = value or self.visit(child_node)
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 104, in visit
    value = self.visit_typedecl(node)
  File "/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py", line 135, in visit_typedecl
    pins[pin.name] = evaluator.eval(expr.strip())
  File "/home/sjalloq/.local/lib/python2.7/site-packages/simpleeval.py", line 309, in eval
    return self._eval(ast.parse(expr.strip()).body[0].value)
  File "/home/sjalloq/.local/lib/python2.7/site-packages/simpleeval.py", line 320, in _eval
    return handler(node)
  File "/home/sjalloq/.local/lib/python2.7/site-packages/simpleeval.py", line 414, in _eval_name
    raise NameNotDefined(node.id, self.expr)
simpleeval.NameNotDefined: 'STM32_D11_SPI_ETHERNET_PIN' is not defined for expression 'STM32_D11_SPI_ETHERNET_PIN'
[14:57:50] 'generate-pins' errored after 842 ms
[14:57:50] ChildProcessError: `python /mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/mbed-js/tools/generate_pins.py NUCLEO_F767ZI` failed with code 1
    at ChildProcess.<anonymous> (/mnt/c/Users/sjalloq.BRIGHTSIGN/Mbed/mbed-js-v2/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
`

**Comment by janjongboom** [comment]
This is now fixed.
