### ISSUE TITLE
Pin name generation failed for NRF52840

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-js-v2#5]
```
janjon01:~/repos/mbed-js-v2 (master) $ python /Users/janjon01/repos/mbed-js-v2/mbed-js/tools/generate_pins.py NRF52840_DK
In file included from /Users/janjon01/repos/mbed-js-v2/mbed-js/tools/../../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/device/nrf.h:79:0,
                 from /Users/janjon01/repos/mbed-js-v2/mbed-js/tools/../../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/hal/nrf_gpio.h:43,
                 from /Users/janjon01/repos/mbed-js-v2/mbed-js/tools/../../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/PinNames.h:43:
/Users/janjon01/repos/mbed-js-v2/mbed-js/tools/../../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/device/nrf52840.h:152:130: fatal error: core_cm4.h: No such file or directory
 #include "core_cm4.h"                               /*!< Cortex-M4 processor and core peripherals                              */
                                                                                                                                  ^
compilation terminated.
Traceback (most recent call last):
  File "/Users/janjon01/repos/mbed-js-v2/mbed-js/tools/generate_pins.py", line 218, in <module>
    main()
  File "/Users/janjon01/repos/mbed-js-v2/mbed-js/tools/generate_pins.py", line 212, in main
    pins = sorted(pins, key=lambda x: (len(x), x.lower()))
TypeError: 'NoneType' object is not iterable
```

**Comment by janjongboom** [comment]
Fixed in https://github.com/ARMmbed/mbed-js-v2/commit/a41fce512ea8eb9692ef3374548db1ef4ffa8bb4
